InitPlayerData()
GetMasterLevel():SetGlobalBGM( "bgm_0" )

--SetKeyInt( "day", 7 )
--SetCurTime( 2 )
--SetKeyInt( "%bookshelf_ok", 1 )
--GetPlayer():EnableDefaultEquipment()
--PlayerPickUp( "data/pickups/pan.pf" )
--PlayerPickUp( "data/pickups/ladder.pf" )
--PlayerPickUp( "data/pickups/stealth.pf" )
--PlayerPickUp( "data/pickups/staff.pf" )
--GetPlayer():RestoreAmmo()
--SetKeyInt( "fan_enabled", 1 )
--SetKeyInt( "fan_1", 1 )
--SetKeyInt( "fan_3", 1 )
--SetKeyInt( "fan_4", 1 )
--SetKeyInt( "fan_pipes", 1 )
--GetMasterLevel():UnlockRegionMap( "3f" )
--GetMasterLevel():UnlockRegionMap( "4f" )
--ForceAllVisible()
